CREATE TABLE [dbo].[COMPRA]
(
[CODCOMP] [char] (8) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CANTCOMP] [int] NULL,
[PAGOCOMP] [decimal] (8, 2) NULL,
[FORMDEPAG] [varchar] (40) COLLATE Modern_Spanish_CI_AS NULL,
[INCOVECOMP] [int] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[COMPRA] ADD CONSTRAINT [CODCOMP_PK] PRIMARY KEY CLUSTERED ([CODCOMP]) ON [PRIMARY]
GO
