CREATE TABLE [dbo].[EMPLEADO]
(
[CODEMP] [char] (5) COLLATE Modern_Spanish_CI_AS NOT NULL,
[NOMEMP] [varchar] (30) COLLATE Modern_Spanish_CI_AS NULL,
[APEEMP] [varchar] (30) COLLATE Modern_Spanish_CI_AS NULL,
[TELEFEMP] [char] (9) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CORREMP] [varchar] (30) COLLATE Modern_Spanish_CI_AS NULL,
[DNIEMP] [char] (8) COLLATE Modern_Spanish_CI_AS NULL,
[ESTEMP] [varchar] (1) COLLATE Modern_Spanish_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[EMPLEADO] ADD CONSTRAINT [CODEMP_PK] PRIMARY KEY CLUSTERED ([CODEMP]) ON [PRIMARY]
GO
