CREATE TABLE [dbo].[SERVICIOS]
(
[CODSERV] [char] (8) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CATSERV] [varchar] (35) COLLATE Modern_Spanish_CI_AS NULL,
[NOMSERV] [varchar] (35) COLLATE Modern_Spanish_CI_AS NULL,
[DESCSERV] [varchar] (60) COLLATE Modern_Spanish_CI_AS NULL,
[PRECSERV] [decimal] (8, 2) NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[SERVICIOS] ADD CONSTRAINT [CODSERV_PK] PRIMARY KEY CLUSTERED ([CODSERV]) ON [PRIMARY]
GO
