CREATE TABLE [dbo].[VENTA]
(
[IDVENT] [int] NOT NULL IDENTITY(1, 1),
[CODCLI] [char] (5) COLLATE Modern_Spanish_CI_AS NULL,
[CODEMP] [char] (5) COLLATE Modern_Spanish_CI_AS NULL,
[IDVENTDET] [int] NULL,
[FECHVENT] [date] NULL,
[TIPMONE] [varchar] (15) COLLATE Modern_Spanish_CI_AS NULL,
[FORMDEPAG] [varchar] (15) COLLATE Modern_Spanish_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VENTA] ADD CONSTRAINT [IDVENT_PK] PRIMARY KEY CLUSTERED ([IDVENT]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VENTA] ADD CONSTRAINT [VENTA_CLIENTE] FOREIGN KEY ([CODCLI]) REFERENCES [dbo].[CLIENTE] ([CODCLI])
GO
ALTER TABLE [dbo].[VENTA] ADD CONSTRAINT [VENTA_EMPLEADO] FOREIGN KEY ([CODEMP]) REFERENCES [dbo].[EMPLEADO] ([CODEMP])
GO
ALTER TABLE [dbo].[VENTA] ADD CONSTRAINT [VENTA_VENTA_DETALLE] FOREIGN KEY ([IDVENTDET]) REFERENCES [dbo].[VENTA_DETALLE] ([IDVENTDET])
GO
