CREATE TABLE [dbo].[VENTA_DETALLE]
(
[IDVENTDET] [int] NOT NULL IDENTITY(1, 1),
[CODSERV] [char] (8) COLLATE Modern_Spanish_CI_AS NULL,
[CODPROD] [char] (8) COLLATE Modern_Spanish_CI_AS NULL,
[FECHSERV] [date] NULL,
[CANTI] [int] NULL,
[NOTAS] [varchar] (45) COLLATE Modern_Spanish_CI_AS NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VENTA_DETALLE] ADD CONSTRAINT [IDVENTDET_PK] PRIMARY KEY CLUSTERED ([IDVENTDET]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[VENTA_DETALLE] ADD CONSTRAINT [VENTA_DETALLE_PRODUCTO] FOREIGN KEY ([CODPROD]) REFERENCES [dbo].[PRODUCTO] ([CODPROD])
GO
ALTER TABLE [dbo].[VENTA_DETALLE] ADD CONSTRAINT [VENTA_DETALLE_SERVICIOS] FOREIGN KEY ([CODSERV]) REFERENCES [dbo].[SERVICIOS] ([CODSERV])
GO
