CREATE TABLE [dbo].[PRODUCTO]
(
[CODPROD] [char] (8) COLLATE Modern_Spanish_CI_AS NOT NULL,
[CODCOMP] [char] (8) COLLATE Modern_Spanish_CI_AS NULL,
[TIPPROD] [varchar] (25) COLLATE Modern_Spanish_CI_AS NULL,
[NOMPROD] [varchar] (25) COLLATE Modern_Spanish_CI_AS NULL,
[DESCPROD] [varchar] (25) COLLATE Modern_Spanish_CI_AS NULL,
[PRECPROD] [decimal] (8, 2) NULL,
[ESTPROD] [varchar] (1) COLLATE Modern_Spanish_CI_AS NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PRODUCTO] ADD CONSTRAINT [CODPROD_PK] PRIMARY KEY CLUSTERED ([CODPROD]) ON [PRIMARY]
GO
ALTER TABLE [dbo].[PRODUCTO] ADD CONSTRAINT [PRODUCTO_COMPRA] FOREIGN KEY ([CODCOMP]) REFERENCES [dbo].[COMPRA] ([CODCOMP])
GO
